# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  hello_config = debug

else ifeq ($(config),release)
  hello_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := hello

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

hello:
ifneq (,$(hello_config))
	@echo "==== Building hello ($(hello_config)) ===="
	@${MAKE} --no-print-directory -C . -f hello.make config=$(hello_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f hello.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   hello"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"